# Generated by Django 4.2 on 2023-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='Görev')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı')),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
